# Generated by Django 5.1.1 on 2024-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
